// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBijpnq5l2CLvtJ0YeqOmFMNHPwCGejJmc',
    appId: '1:775291568783:web:29811e8138d78bc81e66fa',
    messagingSenderId: '775291568783',
    projectId: 'portfolio-d43ec',
    authDomain: 'portfolio-d43ec.firebaseapp.com',
    databaseURL: 'https://portfolio-d43ec-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'portfolio-d43ec.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBamhUh64CxjyGQjAlLl7NZeCRGz_H7YvE',
    appId: '1:775291568783:android:e87dbb79898ff4361e66fa',
    messagingSenderId: '775291568783',
    projectId: 'portfolio-d43ec',
    databaseURL: 'https://portfolio-d43ec-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'portfolio-d43ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-4p3i0_hGrRQgwsgVgD75qo1NWpT_y7Q',
    appId: '1:775291568783:ios:3a0a69ecec28439a1e66fa',
    messagingSenderId: '775291568783',
    projectId: 'portfolio-d43ec',
    databaseURL: 'https://portfolio-d43ec-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'portfolio-d43ec.firebasestorage.app',
    iosBundleId: 'com.example.fireapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-4p3i0_hGrRQgwsgVgD75qo1NWpT_y7Q',
    appId: '1:775291568783:ios:3a0a69ecec28439a1e66fa',
    messagingSenderId: '775291568783',
    projectId: 'portfolio-d43ec',
    databaseURL: 'https://portfolio-d43ec-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'portfolio-d43ec.firebasestorage.app',
    iosBundleId: 'com.example.fireapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBijpnq5l2CLvtJ0YeqOmFMNHPwCGejJmc',
    appId: '1:775291568783:web:f02356af1cadbb7f1e66fa',
    messagingSenderId: '775291568783',
    projectId: 'portfolio-d43ec',
    authDomain: 'portfolio-d43ec.firebaseapp.com',
    databaseURL: 'https://portfolio-d43ec-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'portfolio-d43ec.firebasestorage.app',
  );
}